# Generated by Django 3.1.4 on 2021-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
