# Generated by Django 3.1.5 on 2021-01-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210104_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_place', models.CharField(max_length=1000)),
                ('City_number', models.CharField(max_length=1000)),
            ],
        ),
    ]
