# Generated by Django 3.1.5 on 2021-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_company_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_place',
            new_name='companyplace',
        ),
    ]
